kind: Deployment
apiVersion: apps/v1

metadata:
  namespace: auth
  name: authelia
  labels:
    app: authelia

spec:
  replicas: 1
  selector:
      matchLabels:
        app: authelia  
  template:
    metadata:
      labels:
        app: authelia
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: authelia
          image: authelia/authelia
          ports:
            - containerPort: 9091
              name: http
          volumeMounts:
            - name: nfs-data
              mountPath: /config
              
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: authelia-config-pvc