apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: auth
  name: authelia-config-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi