---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-apikey-secret
    namespace: kube-system
type: Opaque
stringData:
    email: david@davidilie.com
    apiKey: enter api key here
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: traefik-config
    namespace: kube-system
data:
    traefik-config.yaml: |
        http:
          middlewares:
            headers-default:
              headers:
                sslRedirect: true
                browserXssFilter: true
                contentTypeNosniff: true
                forceSTSHeader: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 15552000
                customFrameOptionsValue: SAMEORIGIN
                customRequestHeaders:
                  X-Forwarded-Proto: https
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: acme-certs-traefik
    namespace: kube-system
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 128Mi
