apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: authelia
spec:
    forwardAuth:
        address: http://authelia-service.auth.svc.cluster.local:9091/api/verify?rd=https://auth.davidapps.dev/ # set this to your auth domain
        trustForwardHeader: true
        authResponseHeaders:
            - Remote-User
            - Remote-Groups
            - Remote-Name
            - Remote-Email
